spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superhero?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  sql:
    init:
      platform: mysql
  batch:
    jdbc:
      initialize-schema: always

#parametri file
file:
  nome:
    csv:
      deceduti: bollettino_di_guerra_del_{data}.csv
      rinascite: eroi_rinati_il_{data}.csv
    json: missione_del_{data}.json
  intestazione:
    csv: id_eroe,nome_erore,lista_poteri,nome_evento,data_evento
